### PR TITLE
FORGEPLUGINS-148 Upgrade to java client 2.5.0

### PR DESCRIPTION
**Pull request by VineetReynolds**
Corrected the RestService API usage to reflect changes done for
JBIDE-15429.

Also corrected the use of ICartridge and related classes as done
for JBIDE-13866.

### CODE REVIEW

**Comment by VineetReynolds** [comment]
Please don't merge without testing :smile: This wasn't a simple change to the POM.

**Comment by GrmpCerber** [comment]
Hi @VineetReynolds 

I'm experiencing several problems with the current 2.0.1 client implementation (eg. space in passwords not supported, failure on deep internal errors, ...) so I'd like your pull request to be applied to the baseline plugin ;)

What did you meant by "Please don't merge without testing" ? 
Have you tried it yet ? 
had you experienced any problem ?

Regards

**Comment by VineetReynolds** [comment]
Hi @GrmpCerber , I intended to submit this PR so that it could be tested and verified by the OpenShift team before merging. This is tested not only against some public OpenShift instance.

@lincolnthree can we get someone to test and merge this?

**Comment by lincolnthree** [comment]
@VineetReynolds Yes. We need to find out who is responsible for this plugin now and get them to verify. 

@kraman Do you know who has taken this over?

**Comment by lincolnthree** [comment]
Out of date.

**Pull request closed without merging**
